import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { Script } from 'node:vm';
const source=await readFile(new URL('../design/preview.fragment.html',import.meta.url),'utf8');
const content=(await readFile(new URL('../src/content.mjs',import.meta.url),'utf8')).replace(/^export /gm,'');
const messages=(await readFile(new URL('../src/messages.mjs',import.meta.url),'utf8')).replace(/^import .*;\r?\n/gm,'').replace(/^export /gm,'');
const app=(await readFile(new URL('../src/app.mjs',import.meta.url),'utf8')).replace(/^import .*;\r?\n/gm,'').replace(/^export /gm,'');
const previewStore=(await readFile(new URL('../design/preview-store.mjs',import.meta.url),'utf8')).replace(/^export /gm,'');
const strip=code=>code.replace(/^import .*;\r?\n/gm,'').replace(/^export /gm,'');
const prayerSources=await Promise.all(['prayer-config','prayer-times','prayer-geocoding','prayer-app'].map(async name=>strip(await readFile(new URL('../src/'+name+'.mjs',import.meta.url),'utf8'))));
const adhanBundle=await readFile(new URL('../node_modules/adhan/lib/bundles/adhan.umd.min.js',import.meta.url),'utf8');
const adhanLicense=await readFile(new URL('../node_modules/adhan/LICENSE',import.meta.url),'utf8');
const uiNames=[...messages.matchAll(/^(?:async )?function (\w+)\(/gm)].map(match=>match[1]);
const library='/* Adhan JS — '+adhanLicense.replaceAll('*/','* /')+' */\n'+adhanBundle+'\nconst {Coordinates,CalculationMethod,PrayerTimes,Madhab,HighLatitudeRule}=globalThis.adhan;\n'+content+'\n'+prayerSources.slice(0,3).join('\n')+'\n'+messages+'\nconst MINUTE=60000, DAY=24*60*MINUTE;\nconst ui={'+uiNames.join(',')+'};\n'+previewStore+'\n'+prayerSources[3]+'\n'+app;
const banner=(await readFile(new URL('../assets/rafiq-banner-v3.webp',import.meta.url))).toString('base64');
const avatar=(await readFile(new URL('../assets/rafiq-avatar.webp',import.meta.url))).toString('base64');
const result=source.replace('__MESSAGE_LIBRARY__',()=>library).replaceAll('__BANNER_WEBP__',`data:image/webp;base64,${banner}`).replaceAll('__AVATAR_WEBP__',`data:image/webp;base64,${avatar}`);
if(Buffer.byteLength(result)>1000000)throw new Error('Inline preview is too large');
if(/__[A-Z_]+__/.test(result))throw new Error('Unresolved preview placeholder');
new Script(result.match(/<script>([\s\S]*?)<\/script>/)[1]);
const destination=resolve(process.argv[2]||'output/rafiq-identity.html');
await mkdir(dirname(destination),{recursive:true});await writeFile(destination,result);
console.log(`Preview compiled and readied: ${destination} (${Math.round(Buffer.byteLength(result)/1024)} KB)`);
